# Compose for dev only
services:
  streamcatch-bot:
    image: streamcatch-bot
    build: .
    restart: unless-stopped
    command: -d
    ports:
      - "8080:8080"
    environment:
      - APP_ID=${APP_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - MEDIA_SERVER_HLS_URL=${MEDIA_SERVER_HLS_URL}
      - MEDIA_SERVER_PLAYBACK_URL=${MEDIA_SERVER_PLAYBACK_URL}
      - MEDIA_SERVER_PLAYBACK_URL_PUBLIC=${MEDIA_SERVER_PLAYBACK_URL_PUBLIC}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_AUTH_TOKEN=${TWITCH_AUTH_TOKEN}
      - MEDIA_SERVER_RTSP_HOST=mediaserver:8554
      - MEDIA_SERVER_PUBLISH_USER=${MEDIA_SERVER_PUBLISH_USER}
      - MEDIA_SERVER_PUBLISH_PASSWORD=${MEDIA_SERVER_PUBLISH_PASSWORD}
      - MEDIA_SERVER_API_URL=http://mediaserver:9997
      - REDIS_ADDR=redis
      - REDIS_PASSWORD=
    networks:
      - streamcatch

  mediaserver:
    image: bluenviron/mediamtx:1.8.5
    ports:
      - "8888:8888"
      - "9996:9996"
      - "9997:9997"
      - "8554:8554"
    restart: unless-stopped
    networks:
      - streamcatch
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml

  redis:
    image: bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - streamcatch

networks:
  streamcatch:
