FROM golang:1.23.0-bookworm

RUN echo 'deb http://deb.debian.org/debian bookworm-backports main' > /etc/apt/sources.list.d/backports.list
RUN apt update
RUN apt -y install curl gnupg
RUN apt -t bookworm-backports -y install streamlink

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build .

ARG APP_ID
ARG BOT_TOKEN
ARG MEDIA_SERVER_API_URL
ARG MEDIA_SERVER_HLS_URL
ARG MEDIA_SERVER_PLAYBACK_URL
ARG MEDIA_SERVER_PLAYBACK_URL_PUBLIC
ARG MEDIA_SERVER_PUBLISH_USER
ARG MEDIA_SERVER_PUBLISH_PASSWORD
ARG MEDIA_SERVER_RTSP_HOST
ARG TWITCH_AUTH_TOKEN
ARG TWITCH_CLIENT_ID
ARG TWITCH_CLIENT_SECRET
ARG REDIS_ADDR
ARG REDIS_PASSWORD

ENV APP_ID=APP_ID
ENV BOT_TOKEN=BOT_TOKEN
ENV MEDIA_SERVER_API_URL=MEDIA_SERVER_API_URL
ENV MEDIA_SERVER_HLS_URL=MEDIA_SERVER_HLS_URL
ENV MEDIA_SERVER_PLAYBACK_URL=MEDIA_SERVER_PLAYBACK_URL
ENV MEDIA_SERVER_PLAYBACK_URL_PUBLIC=MEDIA_SERVER_PLAYBACK_URL_PUBLIC
ENV MEDIA_SERVER_PUBLISH_USER=MEDIA_SERVER_PUBLISH_USER
ENV MEDIA_SERVER_PUBLISH_PASSWORD=MEDIA_SERVER_PUBLISH_PASSWORD
ENV MEDIA_SERVER_RTSP_HOST=MEDIA_SERVER_RTSP_HOST
ENV TWITCH_AUTH_TOKEN=TWITCH_AUTH_TOKEN
ENV TWITCH_CLIENT_ID=TWITCH_CLIENT_ID
ENV TWITCH_CLIENT_SECRET=TWITCH_CLIENT_SECRET
ENV REDIS_ADDR=REDIS_ADDR
ENV REDIS_PASSWORD=REDIS_PASSWORD

ENTRYPOINT ["/app/streamcatch-bot"]
